spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: zev
    show-sql: false
  
  flyway:
    schemas: zev
    create-schemas: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/zev
