server:
  port: 8081

spring:
  application:
    name: admin-service
  boot:
    admin:
      client:
        url: http://admin-service:8081
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "http://localhost:8081,http://admin-service:8081"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  endpoint:
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    health:
      show-details: ALWAYS
    loggers:
      enabled: true

logging:
  level:
    de.codecentric.boot.admin: INFO
